"""empty message

Revision ID: 397eeb3b79d5
Revises: ad63322d2c61
Create Date: 2023-10-06 10:17:16.150066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397eeb3b79d5'
down_revision = 'ad63322d2c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_Type', sa.String(), nullable=False),
    sa.Column('vehicle_Year', sa.Integer(), nullable=False),
    sa.Column('vehicle_Name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_vehicles_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.drop_table('vehciles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    op.create_table('vehciles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehcile_Type', sa.VARCHAR(), nullable=False),
    sa.Column('vehcile_Year', sa.INTEGER(), nullable=False),
    sa.Column('vehcile_Name', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_vehciles_owner_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_vehciles')
    )
    op.drop_table('vehicles')
    # ### end Alembic commands ###
