"""empty message

Revision ID: ad63322d2c61
Revises: 943784e85d32
Create Date: 2023-10-05 22:37:00.392293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad63322d2c61'
down_revision = '943784e85d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('First_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_signed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('vehciles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehcile_Type', sa.String(), nullable=False),
    sa.Column('vehcile_Year', sa.Integer(), nullable=False),
    sa.Column('vehcile_Name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_vehciles_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehciles'))
    )
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_event')
    )
    op.drop_table('vehciles')
    op.drop_table('users')
    # ### end Alembic commands ###
