"""empty message

Revision ID: aefcc2576cd9
Revises: 397eeb3b79d5
Create Date: 2023-10-07 14:50:20.183471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefcc2576cd9'
down_revision = '397eeb3b79d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_in_usd', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('price_in_usd')

    # ### end Alembic commands ###
